### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yarocoder**
No edits, just converted .ipynb files to .py files for ease of access and editing on github. .ipynb files remain for reference

### CODE REVIEW

**Comment by yarocoder** [comment]
Last pull request is a gamma flux calculation for a natural boron slab. Please review. Indicates a need for a gamma absorber, like iron oxide, to be in the composite material.

**Comment by yarocoder** [comment]
Minor update

**Comment by tybtab** [comment]
Hey Yaro, I appreciate making the .py files. Your gamma flux calculation in the current state is good (thanks for making it more general by not taylor expanding the exponential). Please change all units to mks or cgs and then I will merge it. It just to make the code more reasonable to read. Also if you can add more comments. For people catching up on learning a programming language, it will be useful if there is an explanation on what you are doing.

**Comment by yarocoder** [comment]
Update with CGS and more comments

**Pull request merged**
